// <auto-generated />
namespace Passion_project_Jaskaran_n01664609.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class RecipeIngredient : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RecipeIngredient));
        
        string IMigrationMetadata.Id
        {
            get { return "202406081511306_RecipeIngredient"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
